#!/bin/bash

# Copyright 2015 Nathan Ross
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#deal with virsh dns
# virsh mangles with dns even in contexts it has
# no intent of fwd'ing it. 
echo -e "nameserver 75.75.75.75\nnameserver 75.75.76.76" > /etc/resolv.conf
if [ -e /dev/sdb1 ]; then
    mount /dev/sdb1 /mnt
    if [ -e /mnt/run.sh ]; then
        chmod +x /mnt/run.sh 
        /mnt/./run.sh 2>&1 >> /var/log/automation_shim
        shutdown now
    fi        
fi
exit 0
