#!/bin/bash

# Copyright 2015 Nathan Ross
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#!/bin/bash
dev=/dev/sdb1
if mount | grep -i $dev > /dev/null
then
    echo "already mounted."
else
    echo "not mounted. mounting"
    mount $dev /nonram
fi

echo "warning! know that the contents of /mnt, /opt, /media, and /var are NOT copied over. thx"
rsync --progress -a /bin /boot /dev /etc /home /initrd.img /lib /lib64 /lost+found /root /sbin /srv /usr /vmlinuz /nonram
